#!/usr/bin/python3
# -*- coding: utf-8 -*-

import argparse
import json
import requests
from datetime import datetime, timezone

parser = argparse.ArgumentParser()
# parser.add_argument("namehas", help="Name of the repo to search for (accepts wildcards)")
parser.add_argument("-r", "--repo", help="Repo name, ie: docker-local")
parser.add_argument("-t", "--github-token", help="Github token for auth")
parser.add_argument("-o", "--organization", help="User organization to elaborate")
parser.add_argument("--delete", help="Backup and delete a repository - Basically clone and zip locally, then delete on GitHub")
parser.add_argument("-q", "--quiet", help="Don't print out the directory structure.", action="store_true", default=False)

args = parser.parse_args()

def main():

    headers = {'Authorization': 'token ' + args.github_token}
    api_baseurl = "https://api.github.com/"
    repos = []

    if args.repo:
        api_url = api_baseurl + 'repos/' + args.organization + "/" + args.repo
        print(api_url)
        repo = (requests.get(api_url, headers=headers)).json()
        
        if "message" in repo:
            if repo["message"] == "Not Found":
                print("Repository not found, please check if it actually exists")
        else:
              t = datetime.strptime(repo['updated_at'], '%Y-%m-%dT%H:%M:%SZ')
              stale_repo_days = (datetime.now(timezone.utc) - t.replace(tzinfo=timezone.utc)).days
              if stale_repo_days > 180:
                  if repo['description']:
                      repos.append(repo['full_name'] + ", " + repo['description'] + ", " + t.strftime('%Y-%m-%d %H:%M') + " --- STALE")
                  else:
                      repos.append(repo['full_name'] + ", " + t.strftime('%Y-%m-%d %H:%M') + " --- STALE")
              else:
                  if repo['description']:
                      repos.append(repo['full_name'] + ", " + repo['description'] + ", " + t.strftime('%Y-%m-%d %H:%M'))
                  else:
                      repos.append(repo['full_name'] + ", " + t.strftime('%Y-%m-%d %H:%M'))
        # 'https://api.github.com/repos/' + repo["full_name"]
        # repo = (requests.get(repo["url"], headers=headers)).json()
        # repos.append(repo['name'] + ", " + repo['updated_at'])
    else:

        # orgs_repos = (requests.get(api_baseurl + '/orgs/' + args.organization + '/repos?per_page=100', headers=headers)).json()
        # repos = json.loads(orgs_repos)
        
        # for repo in orgs_repos:
        #    print(repo['full_name'])
            
        params = {'per_page':100}
        another_page = True

        api_url = api_baseurl + 'orgs/' + args.organization + '/repos'
        orgs_repos = []
        while another_page:
            r = requests.get(api_url, params=params, headers=headers)
            json_response = json.loads(r.text)
            orgs_repos.append(json_response)

            if 'next' in r.links:
                api_url = r.links['next']['url']
            else:
                another_page=False


        for page in orgs_repos:
           for repo in page:
              
              t = datetime.strptime(repo['updated_at'], '%Y-%m-%dT%H:%M:%SZ')
              stale_repo_days = (datetime.now(timezone.utc) - t.replace(tzinfo=timezone.utc)).days

              if stale_repo_days > 1300:
                  if repo['description']:
                      repos.append(repo['full_name'] + ", " + repo['description'] + ", " + t.strftime('%Y-%m-%d %H:%M'))
                  else:
                      repos.append(repo['full_name'] + ", " + t.strftime('%Y-%m-%d %H:%M'))


                  # Show contributors to repo
                  # api_url = api_baseurl + 'repos/' + repo["full_name"] + '/contributors'
                  # contrib = (requests.get(api_url, headers=headers)).json()

                  # for contributor in contrib:
                      # print(contributor['login'], contributor['contributions'])
                  
                  # exit()
              
          


    for repo_det in repos:
        print(repo_det)


    # https://api.github.com/repos/OWNER/REPO/zipball/REF

    # url = "https://api.github.com/XXXX?simple=yes&per_page=100&page=1"
    # res=requests.get(url,headers={"Authorization": git_token})
    # repos=res.json()
    # while 'next' in res.links.keys():
      # res=requests.get(res.links['next']['url'],headers={"Authorization": git_token})
      # repos.extend(res.json())




    exit()
    
    artifact = Artifactory(url=artifact_url, auth=('matteo.migliaccio', 'AKCp8igqzbMzHEiiYF8ADVARTqA2EFct5hzJs5XswFyjLSGLVaJkBKW7HXvM767NiXjByixuR'))

    if args.delete:
        artifact.artifacts.delete(args.delete)
        print(args.delete + " deleted")
        exit()

    repositories = artifact.repositories.list()

    for repo in repositories:

        if args.path:
            if repo.key != args.path:
                continue
        
        repo_info = artifact.repositories.get_repo(repo.key)
        
        if repo_info.rclass == "local":

            # Docker management
            if repo_info.packageType == args.type:
                # if repo_info.key == "docker-local":
                r = requests.get("https://" + af_user + ":" + af_pass + "@artifactory.buildtest.eng.geospock.com/artifactory/api/storage/" + repo_info.key).json()
                repo_lastupdate = (r['lastUpdated'])
                t = datetime.datetime.strptime(repo_lastupdate, '%Y-%m-%dT%H:%M:%S.%fZ')

                repo_children = (r['children'])

                if not args.quiet:
                    print(repo_info.key + " - " + t.strftime('%Y-%m-%d %H:%M') + " --------------------")
                
                for folder in repo_children:
                    if folder['folder'] == True:

                        if not args.quiet:
                            print("    " + folder['uri'])
                        
                        sub_children = requests.get("https://" + af_user + ":" + af_pass + "@artifactory.buildtest.eng.geospock.com/artifactory/api/storage/" + repo_info.key + folder['uri']).json()['children']

                        for sub_folder in sub_children:

                            if sub_folder['folder'] == True:
                                sub_info = artifact.artifacts.info(repo_info.key + "/" + folder['uri'] + "/" + sub_folder['uri'])
                                sub_lastupdate = (sub_info.lastUpdated).strftime('%Y-%m-%d %H:%M')
                                stale_repo_days = (datetime.datetime.now(datetime.timezone.utc) - sub_info.lastUpdated).days

                                if stale_repo_days > 180:

                                    if args.quiet:
                                        print(repo_info.key + folder['uri'] + "/" + sub_folder['uri'] + " set to be deleted (last update " + sub_lastupdate + ")")

                                    sub_lastupdate = sub_lastupdate + " (to be deleted)"
                                    

                                    
                                if not args.quiet:
                                    print("        " + sub_folder['uri'] + " - " + sub_lastupdate)


if __name__ == '__main__': main()
